<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Savings</name>
   <tag></tag>
   <elementGuidId>94e9e701-1a62-4900-830d-76811f6e2d5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='siteNavbar']/li[3]/ul/li[3]/ul/li[4]/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5f1f6df3-a45f-4b8b-beb3-4b4a2c7b6965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5e9f2ca4-a553-408f-9b13-c5d09ae481ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>b869cb65-b463-4b56-9fa5-b82fe35bc03f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Savings</value>
      <webElementGuid>e3871d52-6202-430b-b280-5ee77e25d488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;siteNavbar&quot;)/li[@class=&quot;dropdown menu maindropdown  data-toggle-maindropdown has-submenu open first-menu hover&quot;]/ul[@class=&quot;dropdown-menu level-1&quot;]/li[@class=&quot;dropdown-submenu first-menu open hover&quot;]/ul[@class=&quot;dropdown-menu level-2 Subdropdownchild&quot;]/li[@class=&quot;list-item&quot;]/a[1]/div[@class=&quot;h6&quot;]</value>
      <webElementGuid>ece6d7a4-be2c-46a1-ac8f-1592a9334a1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='siteNavbar']/li[3]/ul/li[3]/ul/li[4]/a/div</value>
      <webElementGuid>5de92e78-9466-4afe-8725-ac0a98e4e069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank'])[1]/following::div[3]</value>
      <webElementGuid>a12deff6-afd1-42fc-b86f-ed5926538372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[1]/following::div[3]</value>
      <webElementGuid>921f2f9c-7864-4ff8-8e66-d432dc90f777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Charge'])[1]/preceding::div[5]</value>
      <webElementGuid>e4028992-3b19-44f1-ae23-2db17dd09ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Borrow'])[1]/preceding::div[5]</value>
      <webElementGuid>6a7dc7e0-3418-4390-9c43-063e636c517c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Savings']/parent::*</value>
      <webElementGuid>9a607df5-f74f-4baa-9b78-fa9bab16b19d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/div</value>
      <webElementGuid>8853b987-6d77-4a5f-9351-64c2651e8b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Savings' or . = 'Savings')]</value>
      <webElementGuid>fbfe7ef0-19b1-4a6f-931a-d29c7f1dd263</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
