<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Money Market Accounts</name>
   <tag></tag>
   <elementGuidId>9b60be5e-040b-4a83-ab73-125ccf664c11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='siteNavbar']/li[3]/ul/li[3]/ul/li[5]/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>444af895-e612-4b41-ae98-724f69cb9fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d4264666-7892-4fa8-b9d5-bf691e269737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>7df17697-aaa3-4ccb-8276-ad42a8f02c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Money Market Accounts</value>
      <webElementGuid>3957d2ad-0598-4f23-aedc-cdf1ac199dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;siteNavbar&quot;)/li[@class=&quot;dropdown menu maindropdown  data-toggle-maindropdown has-submenu open first-menu hover&quot;]/ul[@class=&quot;dropdown-menu level-1&quot;]/li[@class=&quot;dropdown-submenu first-menu open hover&quot;]/ul[@class=&quot;dropdown-menu level-2 Subdropdownchild&quot;]/li[@class=&quot;list-item&quot;]/a[1]/div[@class=&quot;h6&quot;]</value>
      <webElementGuid>ceddd722-383e-4179-82bf-21aa1cc00d90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='siteNavbar']/li[3]/ul/li[3]/ul/li[5]/a/div</value>
      <webElementGuid>07ba9662-d79b-4a3e-ac06-5f26074bbfd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank'])[1]/following::div[4]</value>
      <webElementGuid>d42a7425-142e-4827-9235-dd7e54dd98bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[1]/following::div[4]</value>
      <webElementGuid>6cb9c2fe-6a1b-4459-9042-e1ee28745e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Charge'])[1]/preceding::div[4]</value>
      <webElementGuid>35989cde-deb5-4dac-ab6a-695d572df51b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Borrow'])[1]/preceding::div[4]</value>
      <webElementGuid>ba8b731c-7563-4351-ab00-1e1f4e5ba60a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Money Market Accounts']/parent::*</value>
      <webElementGuid>c1674b46-13a0-4d16-8c9c-90bbb6bc04b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/div</value>
      <webElementGuid>76bd9f5d-b825-48a1-9c94-ce2f43f4f247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Money Market Accounts' or . = 'Money Market Accounts')]</value>
      <webElementGuid>a8da5fa6-5381-4e00-b665-6be6bb4b1246</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
