<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Personal</name>
   <tag></tag>
   <elementGuidId>fe442c83-2ec8-4d62-b684-ad5d52c3d432</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='siteNavbar']/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.dropdown.menu.maindropdown.data-toggle-maindropdown.has-submenu.first-menu > a.dropdown-toggle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c240c7f4-abe5-479d-8e21-9a3d79644ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/personal/</value>
      <webElementGuid>e579b5da-8ffe-485d-91b4-0fc46c619ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle</value>
      <webElementGuid>aaa0f04b-a98f-4387-a8f3-66a750e862c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6be00a9e-b27e-4d7d-bf77-fe440f7d67ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>69a5da98-a2a1-4670-b1eb-9136524ecaef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>85f4ae01-ec34-4be1-aaab-16ec85ad2017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d84f5a30-c9fa-45c7-b049-4c613e37f1a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>adaa991b-5e24-459a-b399-4460e1e9c733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Personal

                                
                        </value>
      <webElementGuid>3deb49c5-5706-4b9d-b032-c284219f2d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;siteNavbar&quot;)/li[@class=&quot;dropdown menu maindropdown  data-toggle-maindropdown has-submenu first-menu&quot;]/a[@class=&quot;dropdown-toggle&quot;]</value>
      <webElementGuid>1b5099be-d0bb-424a-a6a6-401ee18a0d38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='siteNavbar']/li[3]/a</value>
      <webElementGuid>80bb6a0f-4f2e-4281-bae8-a7e4b19894eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Personal')]</value>
      <webElementGuid>7265187c-5eb1-4da7-aee5-ca4e01ed6eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>7f699351-7355-4df3-a03e-8aee99788285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enroll'])[1]/following::a[5]</value>
      <webElementGuid>dbc89150-00b0-4f8c-994a-98762393374a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[1]/preceding::a[3]</value>
      <webElementGuid>f2e00616-edc0-4798-b5d5-9b92d83c32cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank'])[1]/preceding::a[4]</value>
      <webElementGuid>f4b7cba7-98a3-4b09-a98e-02c2e81bb394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Personal']/parent::*</value>
      <webElementGuid>6928b6ba-967b-4631-9a62-38452c6a57c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/personal/')]</value>
      <webElementGuid>44143b3e-af8c-4fd6-8c7e-efa237304a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[3]/a</value>
      <webElementGuid>28e5873c-66df-48c5-8c04-a837c62ec1ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/personal/' and (text() = '
                            Personal

                                
                        ' or . = '
                            Personal

                                
                        ')]</value>
      <webElementGuid>d89340c8-2d6a-4d5d-96d6-5cd3b58bebc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
