<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Certificates of Deposit</name>
   <tag></tag>
   <elementGuidId>790a12d1-8dd9-447b-843e-0dda071c59cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='siteNavbar']/li[3]/ul/li[3]/ul/li[6]/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>983e2d5f-3d50-48cb-b1d3-f5e5921dc7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bcfcc2f3-ee24-4f57-9d0c-fa445b45a27b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>33dc2703-94b8-4c42-a57b-21cacc892f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Certificates of Deposit</value>
      <webElementGuid>4afead9d-7631-4b72-a1c6-6b909287eba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;siteNavbar&quot;)/li[@class=&quot;dropdown menu maindropdown  data-toggle-maindropdown has-submenu open first-menu hover&quot;]/ul[@class=&quot;dropdown-menu level-1&quot;]/li[@class=&quot;dropdown-submenu first-menu open hover&quot;]/ul[@class=&quot;dropdown-menu level-2 Subdropdownchild&quot;]/li[@class=&quot;list-item&quot;]/a[1]/div[@class=&quot;h6&quot;]</value>
      <webElementGuid>4e9fc282-fde1-434a-877d-9df2ca6c0e64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='siteNavbar']/li[3]/ul/li[3]/ul/li[6]/a/div</value>
      <webElementGuid>f7c71245-0987-4244-a642-60ec23c842e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank'])[1]/following::div[5]</value>
      <webElementGuid>b8bef5d0-27d4-44bb-85c7-db02ea0d7123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[1]/following::div[5]</value>
      <webElementGuid>00990b15-9430-47f4-ac7f-3f574d8c3ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Charge'])[1]/preceding::div[3]</value>
      <webElementGuid>55232f60-de94-4b86-874e-021b347e294d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Borrow'])[1]/preceding::div[3]</value>
      <webElementGuid>e5d6ce04-8209-4d1c-a443-21d63ac28a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Certificates of Deposit']/parent::*</value>
      <webElementGuid>6b9ccd37-2c31-489e-a770-9bffdb01d1cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/div</value>
      <webElementGuid>f2890fd4-ad34-4ccf-ba28-babc7e27c43d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Certificates of Deposit' or . = 'Certificates of Deposit')]</value>
      <webElementGuid>2322f318-70df-42dd-8aaa-6bc6dea61eb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
